import type {
  Client,
  ClientAccess,
  ClientBilling,
  ClientMeeting,
  ClientMetric,
  ClientNote,
  ClientStrategy,
  Idea,
  Process,
  Prompt,
  Resource,
  Task,
} from "./types";

// Datos mock de Flare OS V1. Fechas relativas a junio 2026.

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c-universal",
    name: "Universal Solutions Insurance Agency",
    brand: "Universal Solutions",
    industry: "Seguros",
    status: "activo",
    owner: "Juan",
    priority: "alta",
    currentPhase: "produccion",
    healthStatus: "bien",
    progressPercentage: 72,
    description:
      "Agencia de seguros enfocada en la comunidad latina en EE.UU. Contenido educativo sobre seguros de vida, salud y auto.",
    mainGoal: "Posicionar la marca como referente de seguros para latinos",
    monthlyGoal: "Generar 40 leads calificados por mes",
    contentGoal: "16 piezas mensuales (8 reels, 6 carruseles, 2 historias)",
    mainKpi: "Leads generados",
    nextAction: "Aprobar calendario editorial de julio",
    importantLinks: [
      { label: "Instagram", url: "https://instagram.com/universalsolutions" },
      { label: "Drive de marca", url: "https://drive.google.com" },
    ],
    internalNotes:
      "Cliente muy receptivo. Prefiere aprobar contenido los lunes. Tono cercano y educativo.",
    monthlyFee: 1500,
    currency: "USD",
    startDate: "2026-01-12",
    activeServices: ["Contenido orgánico", "Pauta", "Email marketing"],
    activeChannels: ["Instagram", "Facebook", "Email"],
    nextDeliverable: "Calendario editorial de julio",
    lastUpdate: "2026-06-08",
    createdAt: "2026-01-12",
    updatedAt: "2026-06-08",
  },
  {
    id: "c-autozone",
    name: "Autozone",
    brand: "Autozone",
    industry: "Automotriz",
    status: "activo",
    owner: "Sara",
    priority: "alta",
    currentPhase: "publicacion",
    healthStatus: "atencion",
    progressPercentage: 58,
    description:
      "Repuestos y accesorios automotrices. Foco en contenido de producto y promociones mensuales.",
    mainGoal: "Aumentar tráfico a tienda física y WhatsApp",
    monthlyGoal: "300 clics a WhatsApp por mes",
    contentGoal: "12 piezas mensuales con foco en promociones",
    mainKpi: "Clics a WhatsApp",
    nextAction: "Enviar propuesta de campaña de pauta para julio",
    importantLinks: [
      { label: "Instagram", url: "https://instagram.com/autozone" },
    ],
    internalNotes:
      "Atrasos en aprobación de piezas. Insistir con recordatorios los miércoles.",
    monthlyFee: 1200,
    currency: "USD",
    startDate: "2026-02-03",
    activeServices: ["Contenido orgánico", "Pauta"],
    activeChannels: ["Instagram", "Facebook", "WhatsApp"],
    nextDeliverable: "Campaña de promoción de junio",
    lastUpdate: "2026-06-05",
    createdAt: "2026-02-03",
    updatedAt: "2026-06-05",
  },
  {
    id: "c-stx",
    name: "STX",
    brand: "STX",
    industry: "Logística",
    status: "activo",
    owner: "Juan",
    priority: "media",
    currentPhase: "estrategia",
    healthStatus: "bien",
    progressPercentage: 35,
    description:
      "Empresa de logística y transporte. Estamos definiendo la estrategia de contenido B2B en LinkedIn.",
    mainGoal: "Construir autoridad B2B en LinkedIn",
    monthlyGoal: "8 publicaciones LinkedIn + 2 casos de éxito",
    contentGoal: "10 piezas mensuales B2B",
    mainKpi: "Interacciones en LinkedIn",
    nextAction: "Presentar estrategia de contenido Q3",
    importantLinks: [{ label: "LinkedIn", url: "https://linkedin.com" }],
    internalNotes: "Decisor: gerente comercial. Ciclo de aprobación lento.",
    monthlyFee: 900,
    currency: "USD",
    startDate: "2026-04-20",
    activeServices: ["Estrategia", "Contenido B2B"],
    activeChannels: ["LinkedIn"],
    nextDeliverable: "Documento de estrategia Q3",
    lastUpdate: "2026-06-07",
    createdAt: "2026-04-20",
    updatedAt: "2026-06-07",
  },
  {
    id: "c-metalicas",
    name: "Metálicas La 48",
    brand: "Metálicas La 48",
    industry: "Manufactura / Metalmecánica",
    status: "activo",
    owner: "Andrés",
    priority: "media",
    currentPhase: "produccion",
    healthStatus: "atrasado",
    progressPercentage: 44,
    description:
      "Fabricación de estructuras metálicas, puertas y rejas. Contenido de portafolio y antes/después.",
    mainGoal: "Generar cotizaciones por WhatsApp e Instagram",
    monthlyGoal: "25 cotizaciones por mes",
    contentGoal: "8 piezas mensuales de portafolio",
    mainKpi: "Cotizaciones recibidas",
    nextAction: "Recoger material fotográfico de proyectos recientes",
    importantLinks: [
      { label: "Instagram", url: "https://instagram.com/metalicasla48" },
    ],
    internalNotes:
      "Difícil conseguir material. Proponer sesión de fotos mensual fija.",
    monthlyFee: 2500000,
    currency: "COP",
    startDate: "2026-03-15",
    activeServices: ["Contenido orgánico", "Portafolio"],
    activeChannels: ["Instagram", "WhatsApp"],
    nextDeliverable: "Sesión de fotos de proyectos recientes",
    lastUpdate: "2026-05-28",
    createdAt: "2026-03-15",
    updatedAt: "2026-05-28",
  },
  {
    id: "c-sedocare",
    name: "Sedocare",
    brand: "Sedocare",
    industry: "Salud",
    status: "pausado",
    owner: "Sara",
    priority: "baja",
    currentPhase: "pausa",
    healthStatus: "atencion",
    progressPercentage: 60,
    description:
      "Servicios de cuidado y enfermería domiciliaria. Pausa temporal por reestructuración interna del cliente.",
    mainGoal: "Captar familias que necesitan cuidado domiciliario",
    monthlyGoal: "En pausa",
    contentGoal: "En pausa",
    mainKpi: "Leads generados",
    nextAction: "Llamada de reactivación programada para el 20 de junio",
    importantLinks: [],
    internalNotes: "Retomar contacto a mediados de junio. Buen historial de pago.",
    monthlyFee: 800,
    currency: "USD",
    startDate: "2025-11-10",
    activeServices: ["Contenido orgánico"],
    activeChannels: ["Instagram", "Facebook"],
    nextDeliverable: "Plan de reactivación",
    lastUpdate: "2026-05-15",
    createdAt: "2025-11-10",
    updatedAt: "2026-05-15",
  },
  {
    id: "c-ochopilates",
    name: "Ocho Pilates",
    brand: "Ocho Pilates",
    industry: "Fitness / Bienestar",
    status: "prospecto",
    owner: "Juan",
    priority: "alta",
    currentPhase: "onboarding",
    healthStatus: "bien",
    progressPercentage: 15,
    description:
      "Estudio de pilates boutique. Prospecto avanzado: propuesta enviada, en negociación de alcance.",
    mainGoal: "Llenar clases y vender planes mensuales",
    monthlyGoal: "Cerrar contrato en junio",
    contentGoal: "Por definir en onboarding",
    mainKpi: "Reservas de clase",
    nextAction: "Reunión de cierre el 12 de junio",
    importantLinks: [
      { label: "Instagram", url: "https://instagram.com/ochopilates" },
    ],
    internalNotes: "Muy interesados en reels de comunidad y testimonios.",
    monthlyFee: 0,
    currency: "USD",
    startDate: null,
    activeServices: [],
    activeChannels: ["Instagram"],
    nextDeliverable: "Propuesta de alcance firmada",
    lastUpdate: "2026-06-09",
    createdAt: "2026-05-25",
    updatedAt: "2026-06-09",
  },
];

export const MOCK_IDEAS: Idea[] = [
  {
    id: "i-1",
    clientId: "c-universal",
    title: "Carrusel: 5 mitos sobre el seguro de vida",
    description:
      "Desmontar los mitos más comunes que frenan a la comunidad latina a asegurar a su familia.",
    category: "contenido",
    status: "en_produccion",
    priority: "alta",
    format: "carrusel",
    channel: "instagram",
    suggestedDate: "2026-06-15",
    publishDate: null,
    responsible: "Sara",
    notes: "Usar testimonios reales anonimizados.",
    prompt: "p-1",
    references: "https://instagram.com/p/ejemplo-mitos",
    coverImage: "https://picsum.photos/seed/flare-mitos/600/750",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-08",
  },
  {
    id: "i-2",
    clientId: "c-universal",
    title: "Reel: ¿Qué pasa si no tienes seguro de salud en USA?",
    description: "Reel educativo con gancho fuerte sobre costos médicos reales.",
    category: "contenido",
    status: "en_revision_cliente",
    priority: "alta",
    format: "reel",
    channel: "instagram",
    suggestedDate: "2026-06-12",
    publishDate: null,
    responsible: "Andrés",
    notes: "Cliente quiere revisar el guion antes de grabar.",
    prompt: "",
    references: "",
    coverImage: "https://picsum.photos/seed/flare-salud/600/750",
    clientApproval: "cambios_solicitados",
    clientFeedback: "El gancho está fuerte, pero cambien la cifra del minuto 0:05 por la de nuestro plan estándar.",
    createdAt: "2026-06-02",
    updatedAt: "2026-06-09",
  },
  {
    id: "i-3",
    clientId: "c-universal",
    title: "Historia: encuesta sobre tipos de seguro",
    description: "Serie de historias con stickers de encuesta para activar la audiencia.",
    category: "contenido",
    status: "programada",
    priority: "media",
    format: "historia",
    channel: "instagram",
    suggestedDate: null,
    publishDate: "2026-06-11",
    responsible: "Sara",
    notes: "",
    prompt: "",
    references: "",
    coverImage: "https://picsum.photos/seed/flare-encuesta/600/750",
    createdAt: "2026-06-03",
    updatedAt: "2026-06-09",
  },
  {
    id: "i-4",
    clientId: "c-autozone",
    title: "Reel: 3 señales de que tus frenos piden cambio",
    description: "Contenido de valor + CTA a WhatsApp para cotizar repuestos.",
    category: "contenido",
    status: "en_revision_interna",
    priority: "alta",
    format: "reel",
    channel: "instagram",
    suggestedDate: "2026-06-18",
    publishDate: null,
    responsible: "Andrés",
    notes: "Grabar en tienda con mecánico aliado.",
    prompt: "",
    references: "",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-07",
  },
  {
    id: "i-5",
    clientId: "c-autozone",
    title: "Anuncio: promo aceite + filtro junio",
    description: "Pieza de pauta para promoción mensual con precio gancho.",
    category: "campana",
    status: "en_produccion",
    priority: "urgente",
    format: "anuncio",
    channel: "facebook",
    suggestedDate: "2026-06-13",
    publishDate: null,
    responsible: "Laura",
    notes: "Esperando confirmación de precio final.",
    prompt: "",
    references: "",
    coverImage: "https://picsum.photos/seed/flare-promo/600/750",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-09",
  },
  {
    id: "i-6",
    clientId: "c-autozone",
    title: "Carrusel: checklist de viaje por carretera",
    description: "Checklist visual de revisión del carro antes de vacaciones.",
    category: "contenido",
    status: "publicada",
    priority: "media",
    format: "carrusel",
    channel: "instagram",
    suggestedDate: null,
    publishDate: "2026-06-05",
    responsible: "Sara",
    notes: "Buen rendimiento: 230 compartidos.",
    prompt: "",
    references: "",
    coverImage: "https://picsum.photos/seed/flare-checklist/600/750",
    clientApproval: "aprobada",
    createdAt: "2026-05-28",
    updatedAt: "2026-06-06",
  },
  {
    id: "i-7",
    clientId: "c-stx",
    title: "Caso de éxito: entrega crítica en 24 horas",
    description:
      "Post B2B en LinkedIn contando un caso real de operación logística contrarreloj.",
    category: "contenido",
    status: "idea",
    priority: "media",
    format: "blog",
    channel: "linkedin",
    suggestedDate: "2026-06-25",
    publishDate: null,
    responsible: "Juan",
    notes: "Pedir datos y aprobación del cliente final.",
    prompt: "",
    references: "",
    createdAt: "2026-06-06",
    updatedAt: "2026-06-06",
  },
  {
    id: "i-8",
    clientId: "c-stx",
    title: "Estrategia de contenido Q3 LinkedIn",
    description: "Documento de estrategia con pilares, frecuencia y formatos para Q3.",
    category: "estrategia",
    status: "en_produccion",
    priority: "alta",
    format: "otro",
    channel: "linkedin",
    suggestedDate: "2026-06-20",
    publishDate: null,
    responsible: "Juan",
    notes: "",
    prompt: "",
    references: "",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-08",
  },
  {
    id: "i-9",
    clientId: "c-metalicas",
    title: "Reel antes/después: portón industrial",
    description: "Transformación de portón con time-lapse de instalación.",
    category: "contenido",
    status: "idea",
    priority: "alta",
    format: "reel",
    channel: "instagram",
    suggestedDate: "2026-06-22",
    publishDate: null,
    responsible: "Andrés",
    notes: "Bloqueada por falta de material en video.",
    prompt: "",
    references: "",
    createdAt: "2026-06-02",
    updatedAt: "2026-06-02",
  },
  {
    id: "i-10",
    clientId: "c-metalicas",
    title: "Carrusel: catálogo de rejas de seguridad",
    description: "Top 6 diseños de rejas más cotizados con precios desde.",
    category: "contenido",
    status: "aprobada",
    priority: "media",
    format: "carrusel",
    channel: "instagram",
    suggestedDate: "2026-06-17",
    publishDate: null,
    responsible: "Sara",
    notes: "",
    prompt: "",
    references: "",
    coverImage: "https://picsum.photos/seed/flare-rejas/600/750",
    clientApproval: "aprobada",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-07",
  },
  {
    id: "i-11",
    clientId: "c-ochopilates",
    title: "Reel de bienvenida: conoce el estudio",
    description: "Tour del estudio con música tendencia, para arrancar si firman.",
    category: "contenido",
    status: "pausada",
    priority: "media",
    format: "reel",
    channel: "instagram",
    suggestedDate: "2026-06-28",
    publishDate: null,
    responsible: "Juan",
    notes: "Condicionada al cierre del contrato.",
    prompt: "",
    references: "",
    createdAt: "2026-06-09",
    updatedAt: "2026-06-09",
  },
  {
    id: "i-12",
    clientId: null,
    title: "Reel Flare: cómo trabajamos un mes de contenido",
    description: "Contenido de marca propia mostrando el proceso interno de Flare.",
    category: "contenido",
    status: "idea",
    priority: "baja",
    format: "reel",
    channel: "instagram",
    suggestedDate: "2026-06-30",
    publishDate: null,
    responsible: "Laura",
    notes: "Marca propia, sin cliente asociado.",
    prompt: "",
    references: "",
    createdAt: "2026-06-07",
    updatedAt: "2026-06-07",
  },
  {
    id: "i-13",
    clientId: "c-universal",
    title: "Email: recordatorio open enrollment",
    description: "Secuencia corta de 2 emails para la base de datos del cliente.",
    category: "ventas",
    status: "idea",
    priority: "media",
    format: "email",
    channel: "email",
    suggestedDate: "2026-07-01",
    publishDate: null,
    responsible: "Juan",
    notes: "",
    prompt: "",
    references: "",
    createdAt: "2026-06-08",
    updatedAt: "2026-06-08",
  },
  {
    id: "i-14",
    clientId: "c-autozone",
    title: "Historia: detrás de cámaras en bodega",
    description: "Contenido orgánico ligero para humanizar la marca.",
    category: "contenido",
    status: "archivada",
    priority: "baja",
    format: "historia",
    channel: "instagram",
    suggestedDate: null,
    publishDate: null,
    responsible: "Sara",
    notes: "Cliente prefirió no mostrar bodega.",
    prompt: "",
    references: "",
    createdAt: "2026-05-20",
    updatedAt: "2026-05-30",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t-1",
    clientId: "c-universal",
    ideaId: "i-1",
    title: "Diseñar carrusel de mitos en Figma",
    description: "6 slides siguiendo la plantilla de marca de Universal.",
    status: "en_progreso",
    priority: "alta",
    responsible: "Sara",
    dueDate: "2026-06-12",
    area: "diseno",
    notes: "",
    relatedLink: "https://figma.com",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-09",
  },
  {
    id: "t-2",
    clientId: "c-universal",
    ideaId: "i-2",
    title: "Enviar guion del reel a revisión del cliente",
    description: "Guion con gancho, desarrollo y CTA a WhatsApp.",
    status: "en_revision",
    priority: "alta",
    responsible: "Andrés",
    dueDate: "2026-06-10",
    area: "contenido",
    notes: "Cliente revisa los lunes.",
    relatedLink: "",
    createdAt: "2026-06-06",
    updatedAt: "2026-06-09",
  },
  {
    id: "t-3",
    clientId: "c-autozone",
    ideaId: "i-5",
    title: "Confirmar precio final de la promo de junio",
    description: "Llamar al encargado de tienda para validar precio aceite + filtro.",
    status: "bloqueada",
    priority: "urgente",
    responsible: "Laura",
    dueDate: "2026-06-09",
    area: "pauta",
    notes: "Sin respuesta del cliente desde el viernes.",
    relatedLink: "",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-09",
  },
  {
    id: "t-4",
    clientId: "c-autozone",
    ideaId: null,
    title: "Armar reporte de resultados de mayo",
    description: "Reporte mensual con métricas de Instagram y pauta.",
    status: "pendiente",
    priority: "alta",
    responsible: "Sara",
    dueDate: "2026-06-08",
    area: "estrategia",
    notes: "Atrasada: faltan datos de pauta.",
    relatedLink: "",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-08",
  },
  {
    id: "t-5",
    clientId: "c-stx",
    ideaId: "i-8",
    title: "Redactar pilares de contenido Q3",
    description: "Definir 4 pilares con ejemplos de posts por pilar.",
    status: "en_progreso",
    priority: "alta",
    responsible: "Juan",
    dueDate: "2026-06-16",
    area: "estrategia",
    notes: "",
    relatedLink: "",
    createdAt: "2026-06-03",
    updatedAt: "2026-06-09",
  },
  {
    id: "t-6",
    clientId: "c-metalicas",
    ideaId: "i-9",
    title: "Coordinar grabación de instalación de portón",
    description: "Agendar visita a obra con el equipo del cliente.",
    status: "pendiente",
    priority: "alta",
    responsible: "Andrés",
    dueDate: "2026-06-14",
    area: "contenido",
    notes: "Depende de la fecha de instalación del cliente.",
    relatedLink: "",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-04",
  },
  {
    id: "t-7",
    clientId: "c-sedocare",
    ideaId: null,
    title: "Llamada de reactivación con Sedocare",
    description: "Agenda: estado de la reestructuración y plan de reactivación.",
    status: "pendiente",
    priority: "media",
    responsible: "Sara",
    dueDate: "2026-06-20",
    area: "ventas",
    notes: "",
    relatedLink: "",
    createdAt: "2026-05-30",
    updatedAt: "2026-05-30",
  },
  {
    id: "t-8",
    clientId: "c-ochopilates",
    ideaId: null,
    title: "Preparar propuesta final para Ocho Pilates",
    description: "Ajustar alcance y precio según última conversación.",
    status: "en_progreso",
    priority: "urgente",
    responsible: "Juan",
    dueDate: "2026-06-11",
    area: "ventas",
    notes: "Reunión de cierre el 12 de junio.",
    relatedLink: "",
    createdAt: "2026-06-07",
    updatedAt: "2026-06-09",
  },
  {
    id: "t-9",
    clientId: null,
    ideaId: null,
    title: "Actualizar portafolio de Flare en la web",
    description: "Agregar casos de Universal y Autozone al sitio.",
    status: "pendiente",
    priority: "baja",
    responsible: "Laura",
    dueDate: "2026-06-30",
    area: "web",
    notes: "Tarea interna de Flare.",
    relatedLink: "",
    createdAt: "2026-06-02",
    updatedAt: "2026-06-02",
  },
  {
    id: "t-10",
    clientId: "c-universal",
    ideaId: null,
    title: "Programar contenido aprobado de la semana",
    description: "Subir piezas aprobadas a Meta Business Suite.",
    status: "completada",
    priority: "media",
    responsible: "Sara",
    dueDate: "2026-06-08",
    area: "contenido",
    notes: "",
    relatedLink: "",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-08",
  },
];

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "r-1",
    clientId: "c-universal",
    title: "Guía de tono y voz — Universal Solutions",
    type: "referencia",
    category: "cliente",
    content:
      "Tono cercano, educativo y confiable. Hablar de 'tu familia' y 'tu tranquilidad'. Evitar tecnicismos de seguros sin explicarlos. Siempre cerrar con CTA a WhatsApp.",
    externalLink: "",
    tags: ["branding", "tono", "universal"],
    createdAt: "2026-02-01",
    updatedAt: "2026-05-10",
  },
  {
    id: "r-2",
    clientId: null,
    title: "Plantilla de reporte mensual",
    type: "plantilla",
    category: "estrategia",
    content:
      "Estructura: 1) Resumen ejecutivo, 2) Métricas clave vs mes anterior, 3) Contenido top, 4) Aprendizajes, 5) Plan del próximo mes.",
    externalLink: "https://docs.google.com",
    tags: ["reporte", "plantilla", "mensual"],
    createdAt: "2026-01-15",
    updatedAt: "2026-04-02",
  },
  {
    id: "r-3",
    clientId: null,
    title: "Checklist de publicación",
    type: "sop",
    category: "contenido",
    content:
      "1. Copy revisado y sin errores. 2. Pieza aprobada por el cliente. 3. Hashtags según guía. 4. CTA claro. 5. Programada en horario óptimo. 6. Registrada en el calendario de Flare OS.",
    externalLink: "",
    tags: ["checklist", "publicacion"],
    createdAt: "2026-03-01",
    updatedAt: "2026-03-01",
  },
  {
    id: "r-4",
    clientId: "c-autozone",
    title: "Banco de fotos de tienda Autozone",
    type: "link",
    category: "contenido",
    content: "Carpeta con fotos aprobadas de tienda, productos y equipo.",
    externalLink: "https://drive.google.com",
    tags: ["fotos", "autozone"],
    createdAt: "2026-04-10",
    updatedAt: "2026-06-01",
  },
  {
    id: "r-5",
    clientId: null,
    title: "Script de venta para prospectos",
    type: "script",
    category: "ventas",
    content:
      "Apertura: diagnóstico gratuito de redes. Desarrollo: mostrar caso similar. Cierre: propuesta con 2 opciones de alcance.",
    externalLink: "",
    tags: ["ventas", "prospectos"],
    createdAt: "2026-02-20",
    updatedAt: "2026-05-18",
  },
];

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: "p-1",
    clientId: "c-universal",
    title: "Generador de carruseles educativos de seguros",
    category: "contenido",
    promptContent:
      "Actúa como copywriter experto en seguros para la comunidad latina en USA. Crea un carrusel de {num_slides} slides sobre {tema}. Tono cercano y educativo. Slide 1: gancho fuerte. Slides intermedios: un punto por slide con ejemplo cotidiano. Último slide: CTA a WhatsApp. Marca: Universal Solutions.",
    recommendedUse:
      "Usar para generar borradores de carruseles educativos. Revisar siempre datos legales con el cliente.",
    requiredVariables: ["num_slides", "tema"],
    tags: ["carrusel", "seguros", "universal"],
    createdAt: "2026-03-05",
    updatedAt: "2026-05-22",
  },
  {
    id: "p-2",
    clientId: null,
    title: "Guionista de reels con gancho",
    category: "contenido",
    promptContent:
      "Actúa como guionista de reels virales. Escribe un guion de máximo {duracion} segundos sobre {tema} para la marca {marca}. Estructura: gancho en los primeros 2 segundos, desarrollo con 3 puntos rápidos, CTA final a {cta}. Lenguaje hablado, frases cortas.",
    recommendedUse: "Base para cualquier reel de cliente. Ajustar tono según la guía de marca.",
    requiredVariables: ["duracion", "tema", "marca", "cta"],
    tags: ["reel", "guion", "general"],
    createdAt: "2026-02-10",
    updatedAt: "2026-04-15",
  },
  {
    id: "p-3",
    clientId: null,
    title: "Analista de métricas mensuales",
    category: "estrategia",
    promptContent:
      "Actúa como estratega de redes sociales. Con estas métricas del mes: {metricas}, y las del mes anterior: {metricas_anteriores}, escribe un análisis de rendimiento con: 3 hallazgos clave, 2 alertas y 3 recomendaciones accionables para el próximo mes.",
    recommendedUse: "Usar al preparar reportes mensuales de cualquier cliente.",
    requiredVariables: ["metricas", "metricas_anteriores"],
    tags: ["metricas", "reporte", "analisis"],
    createdAt: "2026-03-20",
    updatedAt: "2026-03-20",
  },
  {
    id: "p-4",
    clientId: "c-ochopilates",
    title: "Ideas de contenido para estudio de pilates",
    category: "contenido",
    promptContent:
      "Actúa como creador de contenido fitness. Genera {cantidad} ideas de contenido para un estudio boutique de pilates dirigido a mujeres 25-45. Mezcla: educación postural, comunidad, testimonios y promociones. Para cada idea: título, formato sugerido y gancho.",
    recommendedUse: "Brainstorming mensual si se cierra el contrato con Ocho Pilates.",
    requiredVariables: ["cantidad"],
    tags: ["pilates", "ideas", "fitness"],
    createdAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
];

export const MOCK_PROCESSES: Process[] = [
  {
    id: "pr-1",
    clientId: null,
    title: "Onboarding de cliente nuevo",
    area: "estrategia",
    description:
      "Proceso estándar para arrancar con un cliente nuevo en máximo 2 semanas.",
    steps: [
      "Reunión kickoff: objetivos, audiencia y expectativas",
      "Recolección de accesos y material de marca",
      "Auditoría de redes y competencia",
      "Definición de estrategia y pilares de contenido",
      "Creación del cliente en Flare OS con objetivos y KPIs",
      "Primer calendario editorial aprobado",
    ],
    responsible: "Juan",
    frequency: "Por cliente nuevo",
    status: "activo",
    createdAt: "2026-01-10",
    updatedAt: "2026-04-01",
  },
  {
    id: "pr-2",
    clientId: null,
    title: "Producción de carrusel",
    area: "contenido",
    description: "Flujo de producción de un carrusel desde idea hasta publicación.",
    steps: [
      "Idea validada con cliente asociado en Flare OS",
      "Redacción de copy por slide",
      "Diseño en Figma con plantilla de marca",
      "Revisión interna de calidad",
      "Aprobación del cliente",
      "Programación y registro en calendario",
    ],
    responsible: "Sara",
    frequency: "Por pieza",
    status: "activo",
    createdAt: "2026-01-20",
    updatedAt: "2026-03-12",
  },
  {
    id: "pr-3",
    clientId: null,
    title: "Producción de reels",
    area: "contenido",
    description: "Flujo de producción de reels: guion, grabación, edición y entrega.",
    steps: [
      "Guion con gancho aprobado",
      "Plan de grabación (locación, props, talento)",
      "Grabación",
      "Edición con subtítulos y música",
      "Revisión del cliente",
      "Programación",
    ],
    responsible: "Andrés",
    frequency: "Por pieza",
    status: "activo",
    createdAt: "2026-02-01",
    updatedAt: "2026-05-05",
  },
  {
    id: "pr-4",
    clientId: null,
    title: "Reporte mensual de resultados",
    area: "estrategia",
    description: "Entrega de reporte mensual a cada cliente activo.",
    steps: [
      "Registrar métricas del mes en Flare OS",
      "Comparar contra mes anterior y objetivos",
      "Redactar hallazgos y recomendaciones",
      "Armar presentación con plantilla",
      "Agendar y presentar al cliente",
      "Registrar próxima acción en la ficha del cliente",
    ],
    responsible: "Juan",
    frequency: "Mensual",
    status: "activo",
    createdAt: "2026-01-25",
    updatedAt: "2026-04-20",
  },
  {
    id: "pr-5",
    clientId: "c-autozone",
    title: "Proceso de pauta Autozone",
    area: "pauta",
    description: "Flujo de campañas de pauta mensual para Autozone.",
    steps: [
      "Confirmar promo y presupuesto del mes",
      "Diseñar piezas de anuncio",
      "Montar campaña en Meta Ads",
      "Optimización semanal",
      "Reporte de resultados de pauta",
    ],
    responsible: "Laura",
    frequency: "Mensual",
    status: "borrador",
    createdAt: "2026-05-15",
    updatedAt: "2026-06-01",
  },
];

export const MOCK_METRICS: ClientMetric[] = [
  {
    id: "m-1",
    clientId: "c-universal",
    periodMonth: 4,
    periodYear: 2026,
    instagramFollowers: 4820,
    monthlyReach: 38500,
    impressions: 54200,
    clicks: 980,
    interactions: 2150,
    leadsGenerated: 28,
    whatsappClicks: 145,
    postsPublished: 14,
    reelsPublished: 7,
    carouselsPublished: 5,
    storiesPublished: 18,
    adSpend: 350,
    relevantResults: "Reel de open enrollment llegó a 12k cuentas.",
    performanceNotes: "Buen mes. Los reels educativos superan al resto.",
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
  },
  {
    id: "m-2",
    clientId: "c-universal",
    periodMonth: 5,
    periodYear: 2026,
    instagramFollowers: 5240,
    monthlyReach: 45200,
    impressions: 63800,
    clicks: 1240,
    interactions: 2680,
    leadsGenerated: 36,
    whatsappClicks: 188,
    postsPublished: 16,
    reelsPublished: 8,
    carouselsPublished: 6,
    storiesPublished: 22,
    adSpend: 420,
    relevantResults: "Récord de leads: 36. Carrusel de mitos fue el top del mes.",
    performanceNotes: "Cerca de la meta de 40 leads. Duplicar formato de mitos.",
    createdAt: "2026-06-03",
    updatedAt: "2026-06-03",
  },
  {
    id: "m-3",
    clientId: "c-autozone",
    periodMonth: 4,
    periodYear: 2026,
    instagramFollowers: 8900,
    monthlyReach: 52000,
    impressions: 71500,
    clicks: 1380,
    interactions: 1850,
    leadsGenerated: 0,
    whatsappClicks: 210,
    postsPublished: 11,
    reelsPublished: 4,
    carouselsPublished: 5,
    storiesPublished: 12,
    adSpend: 600,
    relevantResults: "Promo de abril generó 95 clics a WhatsApp.",
    performanceNotes: "El contenido de promociones convierte mejor que el educativo.",
    createdAt: "2026-05-04",
    updatedAt: "2026-05-04",
  },
  {
    id: "m-4",
    clientId: "c-autozone",
    periodMonth: 5,
    periodYear: 2026,
    instagramFollowers: 9150,
    monthlyReach: 48300,
    impressions: 66100,
    clicks: 1190,
    interactions: 1620,
    leadsGenerated: 0,
    whatsappClicks: 245,
    postsPublished: 10,
    reelsPublished: 3,
    carouselsPublished: 5,
    storiesPublished: 10,
    adSpend: 600,
    relevantResults: "245 clics a WhatsApp, mejor mes del año.",
    performanceNotes:
      "Alcance bajó por menos reels publicados. Recuperar ritmo de producción.",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-05",
  },
  {
    id: "m-5",
    clientId: "c-stx",
    periodMonth: 5,
    periodYear: 2026,
    instagramFollowers: 1200,
    monthlyReach: 8500,
    impressions: 12400,
    clicks: 310,
    interactions: 420,
    leadsGenerated: 3,
    whatsappClicks: 12,
    postsPublished: 6,
    reelsPublished: 1,
    carouselsPublished: 2,
    storiesPublished: 4,
    adSpend: 0,
    relevantResults: "Primer post de LinkedIn con 40+ interacciones.",
    performanceNotes: "Aún en fase de estrategia, métricas base registradas.",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-04",
  },
  {
    id: "m-6",
    clientId: "c-metalicas",
    periodMonth: 5,
    periodYear: 2026,
    instagramFollowers: 3400,
    monthlyReach: 15600,
    impressions: 21900,
    clicks: 540,
    interactions: 890,
    leadsGenerated: 18,
    whatsappClicks: 95,
    postsPublished: 6,
    reelsPublished: 2,
    carouselsPublished: 3,
    storiesPublished: 8,
    adSpend: 150,
    relevantResults: "18 cotizaciones, 3 cerradas en venta.",
    performanceNotes:
      "Meta de 25 cotizaciones no alcanzada por baja producción. Falta material.",
    createdAt: "2026-06-06",
    updatedAt: "2026-06-06",
  },
];

// ─── Vista 360 (V1.1) ───────────────────────────────────────────────────────

export const MOCK_STRATEGIES: ClientStrategy[] = [
  {
    id: "st-1",
    clientId: "c-universal",
    brandBrief:
      "Agencia de seguros para la comunidad latina en EE.UU. Educación primero, venta después.",
    targetAudience:
      "Latinos de 28-55 años en EE.UU., familias con hijos, trabajadores independientes sin cobertura.",
    offer: "Asesoría gratuita + pólizas de vida, salud y auto adaptadas a estatus migratorio.",
    tone: "Cercano, educativo, en español sencillo. Nunca alarmista.",
    brandPromise: "Proteger a tu familia sin enredos ni letra pequeña.",
    differentiators:
      "Atención 100% en español, asesores latinos, acompañamiento post-venta.",
    competitors: "Agencias locales de seguros, brokers independientes en Facebook.",
    doGuidelines:
      "Usar testimonios reales. Explicar términos con ejemplos cotidianos. CTA a WhatsApp.",
    dontGuidelines:
      "No prometer precios exactos. No usar miedo extremo. No tecnicismos sin explicar.",
    strategicNotes: "El contenido educativo es el que más leads trae. Doblar reels educativos en Q3.",
    createdAt: "2026-02-01",
    updatedAt: "2026-05-20",
  },
];

export const MOCK_CLIENT_NOTES: ClientNote[] = [
  {
    id: "n-1",
    clientId: "c-universal",
    title: "Aprobación de contenido los lunes",
    content:
      "El cliente revisa y aprueba piezas solo los lunes en la mañana. Enviar todo el viernes anterior.",
    type: "decision",
    isPinned: true,
    responsible: "Juan",
    relatedEntityType: "",
    relatedEntityId: "",
    createdAt: "2026-03-10",
    updatedAt: "2026-03-10",
  },
  {
    id: "n-2",
    clientId: "c-universal",
    title: "Feedback sobre reels de mayo",
    content:
      "Le gustaron los reels educativos. Pide más testimonios de clientes reales para junio.",
    type: "feedback",
    isPinned: false,
    responsible: "Sara",
    relatedEntityType: "",
    relatedEntityId: "",
    createdAt: "2026-06-02",
    updatedAt: "2026-06-02",
  },
  {
    id: "n-3",
    clientId: "c-autozone",
    title: "Problema: aprobaciones lentas",
    content:
      "Las piezas llevan más de una semana en revisión. Escalar con el gerente si sigue así.",
    type: "problema",
    isPinned: true,
    responsible: "Sara",
    relatedEntityType: "",
    relatedEntityId: "",
    createdAt: "2026-06-04",
    updatedAt: "2026-06-04",
  },
];

export const MOCK_ACCESS: ClientAccess[] = [
  {
    id: "a-1",
    clientId: "c-universal",
    platform: "Instagram",
    usernameOrEmail: "universalsolutions",
    url: "https://instagram.com/universalsolutions",
    status: "validado",
    responsible: "Sara",
    requiresSensitiveAccess: false,
    notes: "Acceso vía Meta Business Suite.",
    createdAt: "2026-01-15",
    updatedAt: "2026-01-20",
  },
  {
    id: "a-2",
    clientId: "c-universal",
    platform: "Meta Ads",
    usernameOrEmail: "ads@universalsolutions.com",
    url: "https://business.facebook.com",
    status: "recibido",
    responsible: "Laura",
    requiresSensitiveAccess: true,
    notes: "Falta validar permisos de administrador de pauta.",
    createdAt: "2026-02-01",
    updatedAt: "2026-05-28",
  },
  {
    id: "a-3",
    clientId: "c-autozone",
    platform: "Instagram",
    usernameOrEmail: "autozone",
    url: "https://instagram.com/autozone",
    status: "pendiente",
    responsible: "Sara",
    requiresSensitiveAccess: false,
    notes: "Solicitado por WhatsApp el 5 de junio.",
    createdAt: "2026-06-05",
    updatedAt: "2026-06-05",
  },
];

export const MOCK_MEETINGS: ClientMeeting[] = [
  {
    id: "mt-1",
    clientId: "c-universal",
    meetingDate: "2026-06-02",
    type: "Revisión mensual",
    participants: "Juan, Sara, María (cliente)",
    topics: "Resultados de mayo, calendario de junio, campaña open enrollment.",
    decisions: "Aprobado aumento de 2 reels mensuales. Testimonios reales en junio.",
    pendingItems: "Cliente envía lista de clientes para testimonios.",
    nextMeetingDate: "2026-07-01",
    createdAt: "2026-06-02",
    updatedAt: "2026-06-02",
  },
  {
    id: "mt-2",
    clientId: "c-ochopilates",
    meetingDate: "2026-06-12",
    type: "Cierre de propuesta",
    participants: "Juan, Camila (dueña)",
    topics: "Alcance del servicio, fee mensual, fecha de arranque.",
    decisions: "",
    pendingItems: "Enviar contrato si se aprueba el alcance.",
    nextMeetingDate: null,
    createdAt: "2026-06-09",
    updatedAt: "2026-06-09",
  },
];

export const MOCK_BILLING: ClientBilling[] = [
  {
    id: "b-1",
    clientId: "c-universal",
    monthlyFee: 1500,
    currency: "USD",
    paymentStatus: "pagado",
    billingDate: "2026-06-01",
    includedServices: "Contenido orgánico, pauta y email marketing",
    observations: "Pago puntual vía transferencia.",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-03",
  },
  {
    id: "b-2",
    clientId: "c-autozone",
    monthlyFee: 1200,
    currency: "USD",
    paymentStatus: "pendiente",
    billingDate: "2026-06-15",
    includedServices: "Contenido orgánico y pauta",
    observations: "",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-01",
  },
  {
    id: "b-3",
    clientId: "c-metalicas",
    monthlyFee: 2500000,
    currency: "COP",
    paymentStatus: "vencido",
    billingDate: "2026-06-05",
    includedServices: "Contenido orgánico y portafolio",
    observations: "Recordatorio enviado el 8 de junio.",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-08",
  },
];
